#!/usr/bin/env python3

import subprocess

DNS_IP = "97.107.140.73"
DNS_PORT = 25016
CDN_NAME = "cs5700cdn.example.com"

replica_ip = subprocess.check_output(f"dig @{DNS_IP} -p {DNS_PORT} {CDN_NAME} +short".split()).decode().strip()
print(f"DNS resolved to: {replica_ip}")

print("Pinging")