#!/usr/bin/env bash

HTTP_REPLICAS=(proj4-repl1.5700.network
               proj4-repl2.5700.network
               proj4-repl3.5700.network
               proj4-repl4.5700.network
               proj4-repl5.5700.network
               proj4-repl6.5700.network
               proj4-repl7.5700.network)
HTTP_DIR='http_server'

while getopts p:o:n:u:i: flag
do
    case "${flag}" in
        p) port=${OPTARG};;
        o) origin=${OPTARG};;
        n) name=${OPTARG};;
        u) username=${OPTARG};;
        i) keyfile=${OPTARG};;
    esac
done

for replica in "${HTTP_REPLICAS[@]}"
do
  echo  $replica
	ssh -i "$keyfile" "$username"@"$replica" "du -sh $HTTP_DIR/cache; ls -l $HTTP_DIR/cache | wc -l"
	echo
done