#!/usr/bin/env python3
import argparse
import csv
import time
from urllib.parse import quote

import requests

HTTP_PORT = 25016

REPLICAS = [
    "139.144.30.25",
    "173.255.210.124",
    "139.144.69.56",
    "185.3.95.25",
    "139.162.83.107",
    "192.46.211.228",
    "170.187.240.5",
]


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("-r", type=int, help="the # of the replica to check", required=True)
    args = parser.parse_args()
    return args


def main():
    args = parse_args()
    replica_ip = REPLICAS[args.r - 1]

    with open("pageviews.csv") as article_file:
        reader = csv.DictReader(article_file)
        for row in reader:
            article = quote(row["article"].replace(" ", "_"))
            url = f"http://{replica_ip}:{HTTP_PORT}/{article}"

            resp = requests.get(url)
            if resp.status_code != 200:
                print(f"Failed for /{article}: {resp.status_code}")


if __name__ == '__main__':
    start_time = time.time()
    main()
    print("--- %s seconds ---" % (time.time() - start_time))
