#!/usr/bin/env bash

DNS_SERVER=proj4-dns.5700.network
DNS_DIR='dns_server'
HTTP_REPLICAS=(proj4-repl1.5700.network
               proj4-repl2.5700.network
               proj4-repl3.5700.network
               proj4-repl4.5700.network
               proj4-repl5.5700.network
               proj4-repl6.5700.network
               proj4-repl7.5700.network)
HTTP_DIR='http_server'

while getopts p:o:n:u:i: flag
do
    case "${flag}" in
        p) port=${OPTARG};;
        o) origin=${OPTARG};;
        n) name=${OPTARG};;
        u) username=${OPTARG};;
        i) keyfile=${OPTARG};;
    esac
done

mkdir -p logs

echo "Pulling logs from DNS server"
scp -q -i "$keyfile" "$username"@"$DNS_SERVER":$DNS_DIR/logs.txt logs/dns.txt &

for replica in "${HTTP_REPLICAS[@]}"
do
  echo "Pulling logs from replica $replica"
	scp -q -i "$keyfile" "$username"@"$replica":$HTTP_DIR/logs.txt logs/"$replica".txt &
	echo
done
wait
echo "All logs pulled into logs/"