#!/usr/bin/env bash

while getopts p:o:n:u:i: flag
do
    case "${flag}" in
        p) port=${OPTARG};;
        o) origin=${OPTARG};;
        n) name=${OPTARG};;
        u) username=${OPTARG};;
        i) keyfile=${OPTARG};;
    esac
done
echo 'Deploying the following...'
echo "Port: $port";
echo "origin: $origin";
echo "name: $name";
echo "username: $username";
echo "keyfile: $keyfile";

scp -i ~/.ssh/id_rsa.pub $username@SERVER:/home/USER/FILENAME