#!/usr/bin/env bash

DNS_SERVER = proj4-dns.5700.network
DNS_DIR = 'dns_server'
HTTP_REPLICAS=(proj4-repl1.5700.network)
HTTP_DIR = 'http_server'

while getopts p:o:n:u:i: flag
do
    case "${flag}" in
        p) port=${OPTARG};;
        o) origin=${OPTARG};;
        n) name=${OPTARG};;
        u) username=${OPTARG};;
        i) keyfile=${OPTARG};;
    esac
done

# DNS server deployment
echo "Deploying DNS server..."
echo "Cleaning up existing directories/files"
ssh -i $keyfile $username@$DNS_SERVER "rm -rf ~/$DNS_DIR; mkdir ~/$DNS_DIR/"
echo "Copying DNS files..."
scp -i $keyfile dnsserver $username@$DNS_SERVER:~/$DNS_DIR/
echo "Successfully deployed DNS Server: $username@$DNS_SERVER"

# CDN replica deployment
echo "Deploying CDN replicas..."
for replica in "${HTTP_REPLICAS[@]}"
do
	echo "Deploying Replica: $username@$replica...."
	echo "Cleaning up existing directories..."
	ssh -i $keyfile $username@$replica "rm -rf ~/$HTTP_DIR; mkdir ~/$HTTP_DIR/"
	echo "Copying server file..."
	scp -i $keyfile httpserver $username@$replica:~/$HTTP_DIR/
    echo "Copying page views file..."
	ssh -i $keyfile $username@$host "cd ~/$HTTP_DIR; wget https://piazza.com/redirect/s3?bucket=uploads&prefix=paste%2Fho06biocf8jp0%2Feb3ed044f8c9a064760175e30aee3f0afcc1538ea0bc89cfd55bae71f487c06a%2Fpageviews.csv"
	echo "Deployment complete for replica: $username@$replica\n"
done
echo "All replicas deployed!"



