#!/usr/bin/env python3
import argparse


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", type=str, help="the port number the server will bind to")
    parser.add_argument("-o", type=str, help="the name of the origin server")
    parser.add_argument("-n", type=str, help="CDN-specific name that the server translates to an IP")
    parser.add_argument("-u", type=str, help="the account name for logging in")
    parser.add_argument("-i", type=str, help="path to the private key for logging into nodes")
    args = parser.parse_args()


def main():
    parse_args()


if __name__ == "__main__":
    main()
