#!/usr/bin/env bash

while getopts p:o:n:u:i: flag
do
    case "${flag}" in
        p) port=${OPTARG};;
        o) origin=${OPTARG};;
        n) name=${OPTARG};;
        u) username=${OPTARG};;
        i) keyfile=${OPTARG};;
    esac
done
echo 'Deploying the following...'
echo "Port: $port";
echo "origin: $origin";
echo "name: $name";

# ssh into dns server
ssh -i path_to_key r_r@proj4-dns.5700.network "cd cdn; ./dnsserver -p $port -n $name; ./httpserver -p $port -o $origin"

# "pwd; mkdir cdn; cd cdn; ./dnsserver -p $port -n $name; ./httpserver -p $port -o $origin"

