#!/usr/bin/env bash
DNS_SERVER = proj4-dns.5700.network
DNS_DIR = 'dns_server'
HTTP_REPLICAS=(proj4-repl1.5700.network)
HTTP_DIR = 'http_server'

while getopts p:o:n:u:i: flag
do
    case "${flag}" in
        p) port=${OPTARG};;
        o) origin=${OPTARG};;
        n) name=${OPTARG};;
        u) username=${OPTARG};;
        i) keyfile=${OPTARG};;
    esac
done