#!/usr/bin/env bash
DNS_SERVER=proj4-dns.5700.network
DNS_DIR='dns_server'
HTTP_REPLICAS=(proj4-repl1.5700.network)
HTTP_DIR='http_server'
USERNAME='r_r'

while getopts p:o:n:u:i: flag
do
    case "${flag}" in
        p) port=${OPTARG};;
        o) origin=${OPTARG};;
        n) name=${OPTARG};;
        u) username=${OPTARG};;
        i) keyfile=${OPTARG};;
    esac
done

echo "Shutting down the DNS server"
ssh -i $keyfile $username@$DNS_SERVER pkill -u $USERNAME python3

# clean up
echo "Cleaning up existing directories/files"
ssh -i $keyfile $username@$DNS_SERVER "rm -rf ~/$DNS_DIR"

echo "Shutting down CDN replicas..."
for replica in "${HTTP_REPLICAS[@]}"
do
	echo "Shutting down replica: $username@$replica...."
	ssh -i $keyfile $username@$replica pkill -u $USERNAME python3
	
    echo "Cleaning up existing directories/files"
    ssh -i $keyfile $username@$replica "rm -rf ~/$HTTP_DIR"
done
echo "All replicas running!"